language: node_js

node_js:
  - "12.9.0"

install:
  - npm install
  - npm run bootstrap

script:
  - npm run test:cov

jobs:
  include:
    - stage: Produce Coverage
      node_js: "12.9.0"
      script: npm run test:cov && node coveralls-merge.js && cat ./lcov.info | ./node_modules/coveralls/bin/coveralls.js
